### ISSUE TITLE
Round corner issue?

### ISSUE THREAD

**Issue by long266** [OneUIProject/oneui-core#7]
Hello, I have used this library for one of my projects, but when using it I found some inadequacies.
1. Is there a way to round the 4 corners of the PreferenceFragment(Compat), as I marked in red (screenshot in light mode)
2. when I add a PreferenceCategory with elements inside, the preference background color error(I think so) (dark mode screenshot)
#Edit2 : I found that i need to use seslSetFillBottomEnabled(true); but how i can use RecycleView in PreferenceFragmentCompat, as PreferenceFragmentCompat created its own RecycleView, Thanks
![LIGHT](https://user-images.githubusercontent.com/71440530/171535755-bc1f3878-4d99-466b-9c31-37dcb3eec9d4.PNG)
![DARK](https://user-images.githubusercontent.com/71440530/171535772-d347aecb-fe68-4606-9289-42d444d55455.PNG)

**Comment by BlackMesa123** [comment]
Samsung's PreferenceFragment enables by default rounded corners/fillBottom as long as you add or set a preference xml in the ```onCreatePreferences``` method, you can enable/disable these features with the ```PreferenceFragmentCompat.seslSetRoundedCorner(boolean)``` method.

To set rounded corners, you can either add a PreferenceCategory in your xmls (they have enabled rounded corners by default) or handle them manually per-Preference with the ```Preference.seslSetRoundedBg(int)``` (sets the corners **inside** the choosen Preference) or ```Preference.seslSetSubheaderRoundedBackground(int)``` (sets the corners **in-between** the choosen Preference) methods.

For setting up the RecyclerView of the PreferenceFragment I suggest you to override the ```onViewCreated``` method of the fragment like here:
```java
@Override
public void onViewCreated(View view, Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    getListView().seslSetLastRoundedCorner(true);
}
```

Regarding the bottom rounded corners, these are handled in system frameworks by Samsung and are drawn in the decor view of the window, a flag in the manifest of the app is checked to see whether or not to draw them:
```xml
<meta-data
    android:name="SamsungBasicInteraction"
    android:value="SEP10" />
```

For non-Samsung devices, I suggest you to draw them using a custom [LinearLayout](https://github.com/OneUIProject/oneui-design/blob/main/lib/src/main/java/dev/oneuiproject/oneui/widget/RoundLinearLayout.java) as parent of your layout to emulate the behavior of Samsung's frameworks:
```xml
<dev.oneuiproject.oneui.widget.RoundLinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="0dp"
    android:layout_weight="1"
    android:orientation="vertical"
    app:roundedCorners="bottom_left|bottom_right">

    <androidx.coordinatorlayout.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <!-- ... -->

    </androidx.coordinatorlayout.widget.CoordinatorLayout>

</dev.oneuiproject.oneui.widget.RoundLinearLayout>
```

**Comment by BlackMesa123** [comment]
Just tested myself with the latest 1.1.0 artifact and the default fillBottom works as expected:

<img src="https://user-images.githubusercontent.com/13062958/171586286-d394b9c8-25f9-4840-83b2-41e90b3530d8.jpg" width="37%" />

Make sure you're using "Theme.AppCompat" as your app theme and not "MaterialComponents". For the LinearLayout you can just use the one in the design lib repo (the lib has still not been released so you can't use it unless you compile it yourself) by downloading the class and adding it in your app, you'll also need to add the [attrs resources](https://github.com/OneUIProject/oneui-design/blob/b47a1e70eff7352dd4e22a8aecb2165ed42b2e35/lib/src/main/res/values/attrs.xml#L18) for the widget.

**Comment by long266** [comment]
I made some changes, added RoundedLinearLayout but the problem is still here
![IMG](https://user-images.githubusercontent.com/71440530/171613939-59f41280-13e9-4e85-8901-0acc7e4a3026.jpg)
Also, my project is open-srced, Can you take a look at this
https://github.com/long266/Lumi-Constellation
Thanks !

**Comment by BlackMesa123** [comment]
The issue is in your layout: avoid using both NestedScrollView and RecyclerView since they both have nested scrolling, remove the NestedScrollView from your layout and move the layout_behavior attr in the fragment FrameLayout

**Comment by long266** [comment]
Thank you very much! Problem solved
But I still have one question
CollapsingToolbarLayout will show the correct title when expanded
But in collapsed mode it shows my app name, instead of title i set in app:title

**Comment by BlackMesa123** [comment]
Glad you solved! Try to use `getSupportActionBar(). setDisplayShowTitleEnabled(false)`, but I'm not sure it will work anyway due to how Samsung's CollapsingToolbar works, you may have to set the title on both CollapsingToolbar and Toolbar programmatically

**Comment by long266** [comment]
Thanks. Have a nice day !
