### ISSUE TITLE
Feature Request: About ColorPickerPreference

### ISSUE THREAD

**Issue by long266** [OneUIProject/oneui-core#8]
![Screenshot_2022-06-03_125541](https://user-images.githubusercontent.com/71440530/171796390-9c77a301-3270-4c8b-ac60-7ec101c2d621.jpg)
- I know that it is possible to use the old `ColorPickerPreference`, so I added it to my project
- But it would be better if supported in this new library
- I tried merge it into one and add `app:pickerType`, but compile error because it has same name, so I decided to split it into separate Preference, one for Detailed ColorPicker and one for Classic ColorPicker

**- Here is mine:**
https://github.com/long266/Lumi-Constellation/commit/72a752eed6d3f97c1e1f3fdeb0e4fff4d167ffab
**- Based on:**
Yanndroid [ColorPickerPreference](https://github.com/OneUIProject/OneUI-Design-Library/blob/master/yanndroid/oneui/src/main/java/de/dlyt/yanndroid/oneui/preference/ColorPickerPreference.java)

**Comment by BlackMesa123** [comment]
This repository contains only the Samsung's AndroidX libraries, for all the custom components to be used with this lib please refer to the [oneui-design](https://github.com/OneUIProject/oneui-design) repo, we're working on a separate library that contains all the old library view/widgets+some new neat stuff

**Comment by long266** [comment]
Thanks for explanation
so what about [oneui-design](https://github.com/OneUIProject/oneui-design)
I see it's not available yet
Still using from deprecated repo
