### ISSUE TITLE
DrawerLayout

### ISSUE THREAD

**Issue by long266** [OneUIProject/oneui-core#9]
![Screenshot_2022-06-03_180510](https://user-images.githubusercontent.com/71440530/171861269-8220a9d9-93c4-44e6-a11d-494cf90cb8f3.jpg)
Trying to add DrawerLayout, but got some weird stuff
Is it incomplete, or did I do something wrong

**Comment by long266** [comment]
Here is my layout and build.gradie
![image](https://user-images.githubusercontent.com/71440530/171862177-9fcb9a6d-1dbc-47a0-9113-1097cbce417b.png)
![image](https://user-images.githubusercontent.com/71440530/171862232-224e25ee-e803-4192-9e76-b249ffb9e7c9.png)

**Comment by BlackMesa123** [comment]
The layout seems okay, if you're talking about the drawer UI it looks like that because you manually have to implement:
- Drawer round bg;
- setTranslationX
- Content dim

You can take a look at the oneui-design [DrawerLayout](https://github.com/OneUIProject/oneui-design/blob/main/lib/src/main/java/dev/oneuiproject/oneui/layout/DrawerLayout.java) to see how we did achieve it.

**Comment by long266** [comment]
So I imported [DrawerLayout](https://github.com/OneUIProject/oneui-design/blob/main/lib/src/main/java/dev/oneuiproject/oneui/layout/DrawerLayout.java) and all the components
Got FC on on samsung devices
- Light MODE
```
Caused by: android.view.InflateException: Binary XML file line #8 in com.nhlong.lumi.constellation:layout/long266_main_settings_activity: Error inflating class lumi.constellation.drawer.DrawerLayout
Caused by: android.content.res.Resources$NotFoundException: Can't find ColorStateList from drawable resource ID #0x1080bb6
```
- Dark MODE
```
Caused by: android.view.InflateException: Binary XML file line #8 in com.nhlong.lumi.constellation:layout/long266_main_settings_activity: Error inflating class lumi.constellation.drawer.DrawerLayout
Caused by: android.content.res.Resources$NotFoundException: Can't find ColorStateList from drawable resource ID #0x1080bb5
```
For reference i decompiled samsung framework-res and got this
```
<public type="drawable" name="tw_screen_background_dark" id="0x01080bb5" />
<public type="drawable" name="tw_screen_background_light" id="0x01080bb6" />
```

**Comment by long266** [comment]
Worked on my non-samsung devices
without any problem
![284656294_984030855644666_4258308242082292970_n](https://user-images.githubusercontent.com/71440530/171991785-55008c3c-5435-489d-a6fb-863937e252e1.png)

**Comment by BlackMesa123** [comment]
You might need to add the lib theme attrs in your app theme: [https://github.com/OneUIProject/oneui-design/blob/main/lib/src/main/res/values/themes.xml](https://github.com/OneUIProject/oneui-design/blob/main/lib/src/main/res/values/themes.xml)

**Comment by long266** [comment]
Thanks for your help, i add some in styles.xml, app worked on samsung devices but now i got some stuff about
`android:windowBackground`
without this app fc but worked well on other devices
with it, preference background color is the same as background color
```
<item name="android:windowBackground">@color/sesl_round_and_bgcolor_light</item>
<item name="android:windowBackground">@color/sesl_round_and_bgcolor_dark</item>
```
![screencap1](https://user-images.githubusercontent.com/71440530/171995148-9244bdb8-935f-46c3-b9ea-cf0aae5d7a91.png)
![screencap](https://user-images.githubusercontent.com/71440530/171995150-74d238cd-65ed-4312-bff8-205e1115742a.png)

**Comment by BlackMesa123** [comment]
Just add the `android:background` attr in your RecyclerView/FrameLayout that hosts the fragment and set the color to `sesl_background_color`

**Comment by long266** [comment]
Problem solved but.......
![image](https://user-images.githubusercontent.com/71440530/171995781-8876177a-f742-46a4-af4e-816b6577e5a5.png)

**Comment by BlackMesa123** [comment]
Add `app:elevation="0dp"` in your Drawer's NavigationView.

**Comment by long266** [comment]
After some minimal changes, DrawerLayout doesn't round corner anymore. Any fix for this

**Comment by long266** [comment]
Thank you very very much!, With some of your changes, my app now work well

**Comment by BlackMesa123** [comment]
It's a pleasure! If you're planning to use the components in the oneui-design, I suggest you to manually compile the lib and add it in your project rather than adding every component in your app manually. We hope to release that lib asap
